#!/usr/bin/bash

script_dir=$(dirname "$(realpath "$0")")

filenames=""
filters=""
while [[ ! -z "$1" ]]
do
  if [[ -f "$1" ]]
  then
    filenames="$filenames $1"
  else
    filters="$filters $1"
  fi
  shift
done

if [[ -z "$filenames" ]]
then
  echo No input files given
  exit 1
fi

grep -Hn '^\(\*\|\s*:.*:\)' $filenames | \
  "$script_dir"/fields.sed | \
  "$script_dir"/outline.awk | \
  sort -k1,1 -k2n,2 -t'|' | \
  "$script_dir"/filters.py "$filters"

