#!/usr/bin/bash

awk -F'|' -v OFS='|' '
{
  if ($5 == "NEXT")
    print 1, $0
  else if ($5 == "STARTED")
    print 2, $0
  else if ($5 == "TODO")
    print 3, $0
  else if ($5 == "WAITING")
    print 4, $0
  else if ($5 == "DONE")
    print 5, $0
  else
    print 6, $0
}
' | sort -k1,1 -t'|' -sn | sed 's/[0-9]\+|//'
