#!/usr/bin/bash

awk -F'|' -v OFS='|' '
{
  if ($0 ~ /NEXT/)
    print 1, $0
  else if ($0 ~ /STARTED/)
    print 2, $0
  else if ($0 ~ /TODO/)
    print 3, $0
  else if ($0 ~ /WAITING/)
    print 4, $0
  else if ($0 ~ /DONE/)
    print 5, $0
  else
    print 6, $0
}
' | sort -s | sed 's/[0-9]\+|//'
